### ISSUE TITLE
Support for Pale Moon (long time fork of Firefox without Ruby support)

### ISSUE THREAD

**Issue by ghost** [sakai135/htmlruby-firefox#3]
Hi Sakai135,

Thank you for making this awesome add-on which helped many people learn to read Japanese.

Fx not only implements Ruby now, but maybe you heard the news that they're going to change in a big way, making many old add-ons wither away.

I came here to alert you to a somewhat popular fork of Fx called Pale Moon. It has been gaining traction and is a soundly developed browser. In many ways superior than Fx and much more stable, meaning less development stress and hassle. PM also made a choice to not support Ruby in the core.

With the new developments we expect that PM is going to become more popular, so your support for it would be much appreciated - if you're willing.

May I refer you to the forum thread of the PM project, where I suggested putting Ruby functionality in the core. https://forum.palemoon.org/viewtopic.php?f=13&t=8742

Looks like your newest beta version is very, very good already. We'd appreciate your support immensely. It would also mean that your add-on would continue its purpose of enriching people's lives and easing their Japanese learning experience.

Thank you for your efforts. Cheers to you and I hope to see you down the line on the Pale Moon forum.

Best Regards

**Comment by ghost** [comment]
Please let me clarify that by support I only mean making your add-on compatible with Pale Moon and maybe putting it up on the Pale Moon Addon site (separate from AMO). 

It is of course your choice if you also want to resume development on the add-on going forward with Pale Moon which has no plans to implement Ruby support AND treats addon developers with respect.

**Comment by sakai135** [comment]
Hi, @Supermarkus. Glad you're getting use out of HTML Ruby. Are there any particular issues you're aware of regarding compatibility with Pale Moon?

**Comment by ghost** [comment]
Hi, sakai135, thank you so much for your work and your reply!

There are no issues per se. I am gonna quote from the user Matt A. Tobin on the forum here: 
"Do me a favor and tell him he can do a conditional based on our application name which should be retrievable from Services.jsm so it can be both MozCo and Pale Moon compatibility."

The quote is not directed at you btw, but he explains how one could add Pale Moon support and simultaneously keep support for Mozilla Firefox.

Since your add-on has lost its purpose on Fx I came here to suggest you could revive it on PM, as PM will not introduce Ruby in the core. Maybe we will become somewhat more popular in the future?

Regarding compatibility: Right now it's fine and works in PM, however if you could introduce explicit support for PM (e.g. support our version numbers) it would be the greatest boon ever for our growing community. 

Further down the line, If you would be interested in developing your addon and finish up your new version so that it becomes a final release, PM would be the browser that would give you a reason for doing so.

**Comment by TPS** [comment]
@sakai135 I think you can close this, as I believe @wolfbeast is maintaining this directly in the https://github.com/MoonchildProductions/Pale-Moon codebase.

**Comment by wolfbeast** [comment]
Yes, this particular issue isn't an issue -- I've integrated the extension into the browser (behind a system pref) and although it otherwise follows the extension's code directly, there is no specific Pale Moon compatibility issue in that respect here because it's not used as an installable extension.

Relevant commit: https://github.com/MoonchildProductions/Pale-Moon/commit/88cd6b932e9a4875c0757aa0e2f61552036f8c9b

**Comment by sakai135** [comment]
@wolfbeast Can the Pale Moon integration use a no-restart extension? Newer versions have some important improvements. My main concern is the usage of `DOMNodeInserted` in HTML Ruby 6.x which is deprecated now.

**Comment by wolfbeast** [comment]
> Can the Pale Moon integration use a no-restart extension?

That _should_ be possible; it runs through the same API and same init methods as an installed extension. This may need some testing, though.

**Comment by TPS** [comment]
I use several restartless extensions with Pale Moon, which work perfectly.  I'd be willing to beta-test any updates you'd be willing to send our way, @sakai135, before @wolfbeast, @MoonchildProductions, &/or @Pale-Moon-Addons-Team may consider updating the currently integrated version.

**Comment by wolfbeast** [comment]
A side note about what is deprecated or not: our re-base will (on the DOM side, not the front-end side) be taking Firefox 38 era code. If your current or latest code aims for that or something directly compatible, then updating this would likely be trivial.

**Comment by TPS** [comment]
According to the [readme](https://github.com/sakai135/htmlruby-firefox/blob/master/README.md#L1), support for Ff 38+ is dropped, because

> **Since [Firefox 38 will be implementing ruby annotation support](https://hacks.mozilla.org/2015/03/ruby-support-in-firefox-developer-edition-38/), there won't be anymore updates on HTML Ruby.** Firefox will be the last of the major browsers to implement ruby annotation, but it looks like Firefox will have the best and most complete implementation yet.

But since that rebase will likely take quite a lot of time, in the interim, updating the _current_ PM `ruby` code to the latest improvements that @sakai135 [mentioned above](#issuecomment-202466810) wouldn't probably be remiss.

**Comment by wolfbeast** [comment]
I'm aware that FF38+ support has been dropped. For the very same reason we may no longer need this after the rebase is complete! However, as I mentioned in our issue, in-parser ruby annotation support will likely be less easy to update than this extension, and this extension will likely be more accurate/complete, IF it is maintained.

So what we choose (in-parser or extension) depends very much on if this extension is maintained in the future or not.

By the way, @TPS -- giving your own comments thumbs-ups is really silly and self-important.

**Comment by sakai135** [comment]
@wolfbeast 

This project's aim was always to support the common ruby annotation usage and not to provide spec-accurate or complete support, and hence the name "HTML Ruby" when the official spec only existed as a component of XHTML.

The Firefox 38 ruby annotation support covers the simple ruby annotation with a single `rt` pretty well, which accounts for nearly all of the usage in the wild. Pretty much all HTML Ruby options are possible with only user stylesheets as well for simple ruby annotations.

In that context, I didn't feel that HTML Ruby provides value, which is why I stopped development. I most likely will not be maintaining this extension anymore either.

**Comment by wolfbeast** [comment]
Thank you for making this an easy choice - I will continue to integrate the extension in our current v26 milestone releases, and afterwards will switch to a css-based, parser-integrated implementation in the next milestone.

Thank you for your work on HTML Ruby and your clear response! Our small segment of users in need of Ruby are very thankful for your extension code in use.

**Comment by wolfbeast** [comment]
Feel free to close this issue. All use cases are covered for both the current and future use of ruby annotations in Pale Moon.
